//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genie_logiciel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departements
    {
        public int Id_d { get; set; }
        public string Nom { get; set; }
    }
}
