//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genie_logiciel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imprimantes
    {
        public int Code { get; set; }
        public string DateLiv { get; set; }
        public string DureeGarantie { get; set; }
        public string VitesseImp { get; set; }
        public string Resolution { get; set; }
        public string Marque { get; set; }
        public string Type { get; set; }
        public string Etat { get; set; }
    }
}
