//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genie_logiciel.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GesResEntities : DbContext
    {
        public GesResEntities()
            : base("name=GesResEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Administatifs> Administatifs { get; set; }
        public virtual DbSet<Appel_offre> Appel_offre { get; set; }
        public virtual DbSet<Departements> Departements { get; set; }
        public virtual DbSet<Enseignants> Enseignants { get; set; }
        public virtual DbSet<Fournisseurs> Fournisseurs { get; set; }
        public virtual DbSet<Imprimantes> Imprimantes { get; set; }
        public virtual DbSet<Laboratoires> Laboratoires { get; set; }
        public virtual DbSet<Ordinateurs> Ordinateurs { get; set; }
        public virtual DbSet<Pannes> Pannes { get; set; }
        public virtual DbSet<ResponsableRessources> ResponsableRessources { get; set; }
        public virtual DbSet<Ressources> Ressources { get; set; }
        public virtual DbSet<ServiceMaintenances> ServiceMaintenances { get; set; }
    }
}
