//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genie_logiciel.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pannes
    {
        public int IdPanne { get; set; }
        public int Code { get; set; }
        public string Type { get; set; }
        public string Date_apparition { get; set; }
        public string DateApparition { get; set; }
        public string Explication { get; set; }
        public string Fréquence { get; set; }
        public string Ordre { get; set; }
    }
}
